name: i_am_shit
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/poop.png"
  android: true
  web:
    generate: true
    image_path: "assets/poop.png"
    
  # background_color: "#hexcode"
  # theme_color: "#hexcode"
  # more info: https://pub.dev/packages/flutter_launcher_icons
  # Add to the dependencies:
  # flutter_launcher_icons: ^0.11.0
  # Run the following commands on the terminal to install the above icons.
  # flutter pub get
  # flutter pub run flutter_launcher_icons